import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { SoifError, type FactorSet } from "./types";

/**
 * Loading and validating the factor set.
 *
 * `factors.json` is generated by `scripts/export_factors.py` in the `soif` repo
 * and vendored here (see `scripts/sync-factors.ts`). A factor set is immutable
 * once loaded: every stored estimate is stamped with its `factors_version`, so
 * mutating a loaded set in place would make historical rows irreproducible.
 */

/** Schema majors this code understands. A newer major may have moved fields. */
const SUPPORTED_SCHEMA_MAJOR = 1;

let cached: FactorSet | null = null;

function assertShape(doc: unknown, origin: string): asserts doc is FactorSet {
  if (typeof doc !== "object" || doc === null) {
    throw new SoifError(`${origin}: expected a JSON object`);
  }
  const d = doc as Partial<FactorSet>;

  const missing = (
    [
      "schema_version",
      "factors_version",
      "tiers",
      "token_weights",
      "providers",
      "default_provider",
      "regions",
      "default_region",
      "lifecycle_multiplier",
      "registry",
    ] as const
  ).filter((key) => d[key] === undefined);
  if (missing.length > 0) {
    throw new SoifError(`${origin}: missing required field(s): ${missing.join(", ")}`);
  }

  const major = Number.parseInt(String(d.schema_version).split(".")[0] ?? "", 10);
  if (!Number.isFinite(major)) {
    throw new SoifError(`${origin}: unparseable schema_version "${d.schema_version}"`);
  }
  if (major > SUPPORTED_SCHEMA_MAJOR) {
    // Refusing beats silently reading a moved field as undefined and
    // producing a number that looks plausible.
    throw new SoifError(
      `${origin}: schema_version ${d.schema_version} is newer than this build understands ` +
        `(supports ${SUPPORTED_SCHEMA_MAJOR}.x). Upgrade soif-app or pin an older factor set.`,
    );
  }

  const tiers = d.tiers!;
  if (!Array.isArray(tiers.order) || tiers.order.length === 0) {
    throw new SoifError(`${origin}: tiers.order is empty`);
  }
  for (const tier of tiers.order) {
    if (!tiers.wh_per_1k_output_tokens?.[tier]) {
      throw new SoifError(`${origin}: tier "${tier}" is in order but has no energy triple`);
    }
  }
  if (!tiers.wh_per_1k_output_tokens[tiers.fallback_tier]) {
    throw new SoifError(`${origin}: fallback_tier "${tiers.fallback_tier}" has no energy triple`);
  }
  if (!d.providers![d.default_provider!]) {
    throw new SoifError(`${origin}: default_provider "${d.default_provider}" is not in providers`);
  }
  if (!d.regions![d.default_region!]) {
    throw new SoifError(`${origin}: default_region "${d.default_region}" is not in regions`);
  }
}

/** Parse and validate a factor set from raw JSON text. */
export function parseFactorSet(json: string, origin = "factors.json"): FactorSet {
  let doc: unknown;
  try {
    doc = JSON.parse(json);
  } catch (error) {
    throw new SoifError(`${origin}: invalid JSON — ${(error as Error).message}`);
  }
  assertShape(doc, origin);
  return Object.freeze(doc);
}

/**
 * Resolve the vendored `factors.json`.
 *
 * `SOIF_FACTORS_PATH` overrides it, which is how a self-hosted operator pins a
 * specific factor set (e.g. one downloaded from a soif release) without
 * rebuilding the image.
 */
export function factorsPath(): string {
  const override = process.env.SOIF_FACTORS_PATH;
  if (override) return override;
  // Resolved relative to the package root rather than this module, so it works
  // the same from `next build` output, `tsx`, and the bundled CLI.
  const require = createRequire(import.meta.url);
  return require.resolve("../../../factors.json");
}

/** Load the factor set, memoised for the process lifetime. */
export function loadFactors(): FactorSet {
  if (cached) return cached;
  const path = factorsPath();
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch (error) {
    throw new SoifError(
      `Could not read factors.json at ${path}. ` +
        `Run \`npm run sync:factors\` or set SOIF_FACTORS_PATH. (${(error as Error).message})`,
    );
  }
  cached = parseFactorSet(raw, path);
  return cached;
}

/** Test seam: install a factor set directly, bypassing the filesystem. */
export function setFactors(factors: FactorSet | null): void {
  cached = factors;
}
