import { readFileSync } from "node:fs";
import bundledFactors from "../../../factors.json";
import { SoifError, type FactorSet } from "./types";

/**
 * Loading and validating the factor set.
 *
 * `factors.json` is generated by `scripts/export_factors.py` in the `soif` repo
 * and vendored here (see `scripts/sync-factors.ts`). A factor set is immutable
 * once loaded: every stored estimate is stamped with its `factors_version`, so
 * mutating a loaded set in place would make historical rows irreproducible.
 */

/** Schema majors this code understands. A newer major may have moved fields. */
const SUPPORTED_SCHEMA_MAJOR = 1;

let cached: FactorSet | null = null;

function assertShape(doc: unknown, origin: string): asserts doc is FactorSet {
  if (typeof doc !== "object" || doc === null) {
    throw new SoifError(`${origin}: expected a JSON object`);
  }
  const d = doc as Partial<FactorSet>;

  const missing = (
    [
      "schema_version",
      "factors_version",
      "tiers",
      "token_weights",
      "providers",
      "default_provider",
      "regions",
      "default_region",
      "lifecycle_multiplier",
      "registry",
    ] as const
  ).filter((key) => d[key] === undefined);
  if (missing.length > 0) {
    throw new SoifError(`${origin}: missing required field(s): ${missing.join(", ")}`);
  }

  const major = Number.parseInt(String(d.schema_version).split(".")[0] ?? "", 10);
  if (!Number.isFinite(major)) {
    throw new SoifError(`${origin}: unparseable schema_version "${d.schema_version}"`);
  }
  if (major > SUPPORTED_SCHEMA_MAJOR) {
    // Refusing beats silently reading a moved field as undefined and
    // producing a number that looks plausible.
    throw new SoifError(
      `${origin}: schema_version ${d.schema_version} is newer than this build understands ` +
        `(supports ${SUPPORTED_SCHEMA_MAJOR}.x). Upgrade soif-app or pin an older factor set.`,
    );
  }

  const tiers = d.tiers!;
  if (!Array.isArray(tiers.order) || tiers.order.length === 0) {
    throw new SoifError(`${origin}: tiers.order is empty`);
  }
  for (const tier of tiers.order) {
    if (!tiers.wh_per_1k_output_tokens?.[tier]) {
      throw new SoifError(`${origin}: tier "${tier}" is in order but has no energy triple`);
    }
  }
  if (!tiers.wh_per_1k_output_tokens[tiers.fallback_tier]) {
    throw new SoifError(`${origin}: fallback_tier "${tiers.fallback_tier}" has no energy triple`);
  }
  if (!d.providers![d.default_provider!]) {
    throw new SoifError(`${origin}: default_provider "${d.default_provider}" is not in providers`);
  }
  if (!d.regions![d.default_region!]) {
    throw new SoifError(`${origin}: default_region "${d.default_region}" is not in regions`);
  }
}

/** Parse and validate a factor set from raw JSON text. */
export function parseFactorSet(json: string, origin = "factors.json"): FactorSet {
  let doc: unknown;
  try {
    doc = JSON.parse(json);
  } catch (error) {
    throw new SoifError(`${origin}: invalid JSON — ${(error as Error).message}`);
  }
  assertShape(doc, origin);
  return Object.freeze(doc);
}

/**
 * A path override, when the operator has pinned one.
 *
 * `SOIF_FACTORS_PATH` is how a self-hosted deployment pins a specific factor
 * set — one downloaded from a `soif` release, say — without rebuilding.
 */
export function factorsPath(): string | null {
  return process.env.SOIF_FACTORS_PATH?.trim() || null;
}

/**
 * Load the factor set, memoised for the process lifetime.
 *
 * The vendored `factors.json` is imported statically rather than read from
 * disk. Bundlers rewrite `require.resolve` into an internal module id, so a
 * path-based load works under `tsx` and then fails in the production build —
 * and a dashboard that cannot find its factors is a dashboard that cannot show
 * a number. Importing it makes the factor set part of the artifact.
 */
export function loadFactors(): FactorSet {
  if (cached) return cached;

  const path = factorsPath();
  if (path) {
    let raw: string;
    try {
      raw = readFileSync(path, "utf8");
    } catch (error) {
      throw new SoifError(
        `SOIF_FACTORS_PATH is set to ${path} but it could not be read (${(error as Error).message}). ` +
          "Unset it to use the bundled factor set.",
      );
    }
    cached = parseFactorSet(raw, path);
    return cached;
  }

  // Re-validated rather than trusted: the vendored file is synced from the
  // soif repo by a script, and a partial sync should fail loudly here.
  assertShape(bundledFactors, "bundled factors.json");
  cached = Object.freeze(bundledFactors as FactorSet);
  return cached;
}

/** Test seam: install a factor set directly, bypassing the filesystem. */
export function setFactors(factors: FactorSet | null): void {
  cached = factors;
}
